services:
  frontend:
    build:
      context: "."
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_HOST=0.0.0.0
    command: npm run dev
